include: package:flutter_lints/flutter.yaml

linter:
  rules:
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
    avoid_print: false
    unnecessary_this: true
    always_use_package_imports: true
    prefer_final_fields: true
    prefer_single_quotes: true
    avoid_unnecessary_containers: true
    use_key_in_widget_constructors: true
